### ISSUE TITLE
General CSS Styling Checklist

### ISSUE THREAD

**Issue by thinhgvo** [thinhgvo/sp23-cse110-lab3#1]
- [x] Elements Color
- [x] Comment
- [x] Background color
- [x] Unit:
    - [x] 3 unique relative units
    - [x] 3 unique absolute units
- [x] Box Model:
    - [x] Margins:
        - [x] Long
        - [x] Short
        - [x] Auto margins
    - [x] Padding:
        - [x] Long
        - [x] Short
    - [x] Borders:
        - [x] Border-style
        - [x] Border-color
        - [x] Border-width
        - [x] Border-radius
- [x] Text:
    - [x] color
    - [x] text-decoration
    - [x] text-align
- [x] Display:
    - [x] None, block, inline-block, inline (Select 2) Apply these to the display properties
- [x] Sizing:
    - [x] Height
    - [x] Width
    - [x] Max-width
    - [x] Min-width
- [x] Position:
    - [x] Static, relative, fixed, absolute, sticky (Apply these to the position properties)
- [x] Pseudo-class
    - [x] :hover
    - [x] :active
- [x] Layouts:
    - [x] Flexbox:
        - [x] Apply flex to display property
        - [x] Must have more than two children within the element that is using Flexbox. Must use a minimum of three of the flexbox-related attributes
    - [x] Grid:
        - [x] Apply grid to display property
        - [x] Must have more than two children within the element that is using Grid. Must use a minimum of three of the grid-related attributes
- [x] Responsiveness:
    - [x] At least one query based on the screen width
- [x] Fonts:
    - [x] Load a 3rd party font in either CSS or HTML.
